using Attendance.Api.Modules.Reporting.Application;
using Attendance.Api.Modules.Reporting.Contracts;
using Attendance.Api.Modules.Attendance.Application;
namespace Attendance.Api.Modules.Reporting.Endpoints;
public static class ReportingEndpointRouteBuilderExtensions{
 public static IEndpointRouteBuilder MapReportingEndpoints(this IEndpointRouteBuilder e){var g=e.MapGroup("/api/reports").WithTags("Reports").RequireAuthorization("AdminOnly");g.MapGet("/attendance",Get).WithName("GetAttendanceReport").WithSummary("Get attendance report").Produces<AttendanceReportResponse>();g.MapGet("/attendance.xlsx",Excel).WithName("ExportAttendanceExcel").WithSummary("Export attendance report as Excel").Produces<byte[]>(StatusCodes.Status200OK, contentType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");g.MapGet("/attendance.pdf",Pdf).WithName("ExportAttendancePdf").WithSummary("Export attendance report as PDF").Produces<byte[]>(StatusCodes.Status200OK, contentType:"application/pdf");return e;}
 static async Task<IResult> Get(DateOnly? from,DateOnly? to,Guid? employeeId,AttendanceReportService s,CancellationToken ct){var v=AttendanceRequestValidator.ValidateRange(from,to);return !v.IsValid?TypedResults.ValidationProblem(v.Errors):TypedResults.Ok(await s.GetAsync(v.Value!.From,v.Value.To,employeeId,ct));}
 static async Task<IResult> Excel(DateOnly? from,DateOnly? to,Guid? employeeId,AttendanceReportService s,CancellationToken ct){var v=AttendanceRequestValidator.ValidateRange(from,to);if(!v.IsValid)return TypedResults.ValidationProblem(v.Errors);var r=await s.GetAsync(v.Value!.From,v.Value.To,employeeId,ct);return Results.File(s.Excel(r),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",$"Reporte-Asistencia-{r.From:yyyy-MM-dd}-a-{r.To:yyyy-MM-dd}.xlsx");}
 static async Task<IResult> Pdf(DateOnly? from,DateOnly? to,Guid? employeeId,AttendanceReportService s,CancellationToken ct){var v=AttendanceRequestValidator.ValidateRange(from,to);if(!v.IsValid)return TypedResults.ValidationProblem(v.Errors);var r=await s.GetAsync(v.Value!.From,v.Value.To,employeeId,ct);return Results.File(s.Pdf(r),"application/pdf",$"Reporte-Asistencia-{r.From:yyyy-MM-dd}-a-{r.To:yyyy-MM-dd}.pdf");}
}
