<script setup lang="ts">
import Button from 'primevue/button'
import Column from 'primevue/column'
import DataTable from 'primevue/datatable'
import Dialog from 'primevue/dialog'
import Paginator from 'primevue/paginator'
import Tag from 'primevue/tag'
import { computed, reactive, ref } from 'vue'
import AppEmptyState from '@/components/state/AppEmptyState.vue'
import AppErrorState from '@/components/state/AppErrorState.vue'
import AppLoadingState from '@/components/state/AppLoadingState.vue'
import AppPageHeader from '@/components/app/AppPageHeader.vue'
import { listAuditEvents, type AuditEvent } from '@/modules/auditing/audit.service'
import { getUserFriendlyApiError } from '@/services/api-errors'

const events = ref<AuditEvent[]>([]), loading = ref(false), error = ref<string | null>(null), total = ref(0), selected = ref<AuditEvent | null>(null)
const filters = reactive({ from: '', to: '', action: '', entityType: '', page: 1, pageSize: 50 })
const actionLabels: Record<string, string> = { CreateEmployee: 'Empleado creado', UpdateEmployee: 'Empleado actualizado', ActivateEmployee: 'Empleado activado', DeactivateEmployee: 'Empleado desactivado', CreateAbsence: 'Ausencia registrada', UpdateAbsence: 'Ausencia actualizada', CancelAbsence: 'Ausencia cancelada', CreateWorkCalendarDay: 'Día calendario creado', UpdateWorkCalendarDay: 'Día calendario actualizado', DeleteWorkCalendarDay: 'Día calendario eliminado', BulkConfigureWorkCalendar: 'Calendario configurado', CreateWorkAssignment: 'Asignación creada', UpdateWorkAssignment: 'Asignación actualizada', CancelWorkAssignment: 'Asignación cancelada', CreateCheckpoint: 'Checkpoint creado', UpdateCheckpoint: 'Checkpoint actualizado', ActivateCheckpoint: 'Checkpoint activado', DeactivateCheckpoint: 'Checkpoint desactivado', CreateUser: 'Cuenta creada', UpdateUserRole: 'Rol de cuenta actualizado', ActivateUser: 'Cuenta activada', DeactivateUser: 'Cuenta desactivada', ResetUserPassword: 'Contraseña restablecida' }
const entityLabels: Record<string, string> = { Employee: 'Empleado', Absence: 'Ausencia', WorkCalendarDay: 'Calendario laboral', EmployeeWorkAssignment: 'Asignación', Checkpoint: 'Checkpoint', ApplicationUser: 'Cuenta de usuario' }
const actionOptions = computed(() => Object.entries(actionLabels).map(([value, label]) => ({ value, label })))
const entityOptions = computed(() => Object.entries(entityLabels).map(([value, label]) => ({ value, label })))
function actionLabel(value: string): string { return actionLabels[value] ?? value }
function entityLabel(value: string): string { return entityLabels[value] ?? value }
function formatDate(value: string): string { return new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/Lima' }).format(new Date(value)) }
function detail(event: AuditEvent): string { if (!event.metadata) return 'Sin detalle adicional.'; return Object.entries(event.metadata).map(([key, value]) => `${labelForKey(key)}: ${String(value)}`).join(' · ') }
function labelForKey(key: string): string { return ({ employeeCode: 'Código', employeeId: 'Empleado', targetUserId: 'Cuenta', from: 'Desde', to: 'Hasta', date: 'Fecha', type: 'Tipo', dayType: 'Tipo de día', role: 'Rol', created: 'Creados', updated: 'Actualizados', skipped: 'Omitidos', overwriteExisting: 'Sobrescribir existentes', code: 'Código' } as Record<string, string>)[key] ?? key }
async function load(): Promise<void> { loading.value = true; try { const result = await listAuditEvents({ from: filters.from || undefined, to: filters.to || undefined, action: filters.action || undefined, entityType: filters.entityType || undefined, page: filters.page, pageSize: filters.pageSize }); events.value = result.items; total.value = result.total; error.value = null } catch (exception) { error.value = getUserFriendlyApiError(exception) } finally { loading.value = false } }
function applyFilters(): void { filters.page = 1; void load() }
function changePage(event: { page: number; rows: number }): void { filters.page = event.page + 1; filters.pageSize = event.rows; void load() }
void load()
</script>

<template><section><AppPageHeader title="Auditoría" description="Trazabilidad de las acciones administrativas del sistema."/><div class="app-surface absence-filters"><label>Desde<input v-model="filters.from" type="date"/></label><label>Hasta<input v-model="filters.to" type="date"/></label><label>Acción<select v-model="filters.action"><option value="">Todas</option><option v-for="option in actionOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label>Tipo de entidad<select v-model="filters.entityType"><option value="">Todos</option><option v-for="option in entityOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><div class="absence-card__actions"><Button label="Filtrar" @click="applyFilters"/></div></div><AppLoadingState v-if="loading" label="Cargando auditoría..."/><AppErrorState v-else-if="error" title="No pudimos cargar la auditoría." :description="error" @retry="load"/><AppEmptyState v-else-if="!events.length" title="No hay eventos para estos filtros." description="Las acciones administrativas aparecerán aquí."/><div v-else class="absence-list"><DataTable :value="events" class="absence-table"><Column header="Fecha y hora"><template #body="{ data }">{{ formatDate(data.occurredAt) }}</template></Column><Column header="Usuario"><template #body="{ data }">{{ data.actor.displayName }}</template></Column><Column header="Acción"><template #body="{ data }"><Tag :value="actionLabel(data.action)" severity="info"/></template></Column><Column header="Recurso"><template #body="{ data }">{{ entityLabel(data.entityType) }}</template></Column><Column header="Detalle"><template #body="{ data }">{{ detail(data) }}</template></Column><Column header=""><template #body="{ data }"><Button label="Ver detalle" text @click="selected = data"/></template></Column></DataTable><div class="absence-cards"><article v-for="event in events" :key="event.id" class="app-surface absence-card"><strong>{{ actionLabel(event.action) }}</strong><span>{{ formatDate(event.occurredAt) }}</span><span>{{ event.actor.displayName }} · {{ entityLabel(event.entityType) }}</span><small>{{ detail(event) }}</small><Button label="Ver detalle" text @click="selected = event"/></article></div><Paginator :first="(filters.page - 1) * filters.pageSize" :rows="filters.pageSize" :total-records="total" :rows-per-page-options="[25, 50, 100, 200]" @page="changePage"/></div><Dialog :visible="Boolean(selected)" modal class="app-form-dialog" header="Detalle de auditoría" @update:visible="selected = null"><div v-if="selected" class="absence-form"><p><strong>Usuario:</strong> {{ selected.actor.displayName }}</p><p><strong>Fecha:</strong> {{ formatDate(selected.occurredAt) }}</p><p><strong>Acción:</strong> {{ actionLabel(selected.action) }}</p><p><strong>Entidad:</strong> {{ entityLabel(selected.entityType) }}</p><p><strong>Detalle:</strong> {{ detail(selected) }}</p></div></Dialog></section></template>
